### ISSUE TITLE
Actions from tic.yml are failing

### ISSUE THREAD

**Issue by kapsner** [miracum/misc-diztools#1]
A dependency seems to be missing dependency: https://github.com/miracum/misc-diztools/actions/runs/4632463316/jobs/8196546790#step:12:92

**Comment by joundso** [comment]
@kapsner Thanks for the hint! Will have a look into this.

**Comment by kapsner** [comment]
Thx; seems as if there is yet another dependency missing: https://github.com/miracum/misc-diztools/actions/runs/4645136868/jobs/8220821597#step:12:49
(btw: dizutils seems to be affected as well).
